import type { PageData, FormField } from './pageCrawler';

export interface GenerationResult {
  code: string;
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheWriteTokens: number;
}

/**
 * Generates Playwright tests from crawled page data.
 *
 * MOCK MODE: streams a locally-built test file to demonstrate the full pipeline
 * without making real API calls. Swap this implementation for the Anthropic SDK
 * version (see aiGenerator.real.ts.example) once you have an API key.
 */
export async function generateTests(
  pageData: PageData,
  onChunk: (text: string) => void
): Promise<GenerationResult> {
  const code = buildMockTest(pageData);

  // Simulate SSE streaming — emit realistic ~45-char chunks with small delays
  const CHUNK_SIZE = 45;
  for (let i = 0; i < code.length; i += CHUNK_SIZE) {
    onChunk(code.slice(i, i + CHUNK_SIZE));
    await delay(10);
  }

  return {
    code,
    inputTokens: Math.round(code.length / 4) + 380,
    outputTokens: Math.round(code.length / 4),
    cacheReadTokens: 380, // simulated cache hit on static system prompt
    cacheWriteTokens: 0,
  };
}

function delay(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

// ── Mock test builder ────────────────────────────────────────────────────────

function buildMockTest(pageData: PageData): string {
  const url = pageData.finalUrl || pageData.url;
  const label = pageData.title || new URL(url).hostname;

  const blocks: string[] = [
    `import { test, expect } from '@playwright/test';`,
    ``,
    `// Generated by ai-test-generator (mock mode — no real API call)`,
    `// Target: ${url}`,
    ``,
    `test.describe('${escStr(label)}', () => {`,
    `  test.beforeEach(async ({ page }) => {`,
    `    await page.goto('${url}');`,
    `  });`,
    ``,
    pageLoadBlock(pageData),
  ];

  if (pageData.hasAuth && pageData.forms.length > 0) {
    blocks.push(authBlock(pageData));
  }

  if (pageData.hasSearch) {
    blocks.push(searchBlock(pageData));
  }

  if (pageData.buttons.length > 0) {
    blocks.push(buttonsBlock(pageData));
  }

  if (pageData.links.length > 0) {
    blocks.push(linksBlock(pageData));
  }

  blocks.push(`});`);
  return blocks.join('\n');
}

function pageLoadBlock(pageData: PageData): string {
  const lines = [
    `  test('loads the page successfully', async ({ page }) => {`,
    `    await expect(page).toHaveTitle(/${escapeRegex(pageData.title)}/i);`,
    `    await expect(page.locator('body')).toBeVisible();`,
  ];

  if (pageData.headings.length > 0) {
    const h = pageData.headings[0];
    lines.push(
      `    await expect(page.getByRole('heading', { name: /${escapeRegex(h.text)}/i }).first()).toBeVisible();`
    );
  }

  lines.push(`  });`, ``);
  return lines.join('\n');
}

function authBlock(pageData: PageData): string {
  const form = pageData.forms[0];
  const userField = form.fields.find(
    f => f.type === 'text' || /user|email|login/.test(f.name + f.id)
  );
  const passField = form.fields.find(f => f.type === 'password');
  const submit = form.submitButtons[0];

  const userSel = userField ? fieldSelector(userField) : `page.locator('input[type="text"]').first()`;
  const passSel = passField ? fieldSelector(passField) : `page.locator('input[type="password"]')`;
  const btnSel = submit?.testId
    ? `page.locator('[data-testid="${submit.testId}"]')`
    : submit?.text
      ? `page.getByRole('button', { name: '${escStr(submit.text)}' })`
      : `page.locator('input[type="submit"], button[type="submit"]').first()`;

  return [
    `  test.describe('authentication', () => {`,
    `    test('shows login form elements', async ({ page }) => {`,
    `      await expect(${userSel}).toBeVisible();`,
    `      await expect(${passSel}).toBeVisible();`,
    `      await expect(${btnSel}).toBeEnabled();`,
    `    });`,
    ``,
    `    test('rejects empty credentials', async ({ page }) => {`,
    `      await ${btnSel}.click();`,
    `      await expect(page.locator('body')).toContainText(/required|error|invalid/i);`,
    `    });`,
    ``,
    `    test('rejects invalid credentials', async ({ page }) => {`,
    `      await ${userSel}.fill('invalid_user_123');`,
    `      await ${passSel}.fill('wrong_password');`,
    `      await ${btnSel}.click();`,
    `      await expect(page.locator('body')).toContainText(/error|invalid|incorrect/i);`,
    `    });`,
    `  });`,
    ``,
  ].join('\n');
}

function searchBlock(pageData: PageData): string {
  const field =
    pageData.inputs.find(i => i.type === 'search' || i.name === 'q' || /search/i.test(i.placeholder)) ??
    pageData.forms.flatMap(f => f.fields).find(f => f.type === 'search' || /search/i.test(f.placeholder));

  const sel = field
    ? fieldSelector(field)
    : `page.locator('input[type="search"], input[name="q"]').first()`;

  return [
    `  test.describe('search', () => {`,
    `    test('search input is present and interactive', async ({ page }) => {`,
    `      await expect(${sel}).toBeVisible();`,
    `      await ${sel}.fill('test query');`,
    `      await ${sel}.press('Enter');`,
    `    });`,
    `  });`,
    ``,
  ].join('\n');
}

function buttonsBlock(pageData: PageData): string {
  const lines = [`  test.describe('interactive elements', () => {`];

  for (const btn of pageData.buttons.slice(0, 4)) {
    if (!btn.text.trim()) continue;
    const sel = btn.testId
      ? `page.locator('[data-testid="${btn.testId}"]')`
      : `page.getByRole('${btn.tag === 'a' ? 'link' : 'button'}', { name: '${escStr(btn.text.slice(0, 40))}' }).first()`;

    lines.push(
      `    test('"${escStr(btn.text.slice(0, 35))}" is visible and enabled', async ({ page }) => {`,
      `      await expect(${sel}).toBeVisible();`,
      `    });`,
      ``
    );
  }

  lines.push(`  });`, ``);
  return lines.join('\n');
}

function linksBlock(pageData: PageData): string {
  const lines = [
    `  test.describe('navigation', () => {`,
    `    test('key navigation links are present', async ({ page }) => {`,
  ];

  for (const link of pageData.links.filter(l => l.text.trim()).slice(0, 5)) {
    lines.push(
      `      await expect(page.getByRole('link', { name: '${escStr(link.text.slice(0, 40))}' }).first()).toBeVisible();`
    );
  }

  lines.push(`    });`, `  });`, ``);
  return lines.join('\n');
}

// ── Selector helpers ─────────────────────────────────────────────────────────

function fieldSelector(field: Partial<FormField>): string {
  if (field.testId) return `page.locator('[data-testid="${field.testId}"]')`;
  if (field.id)     return `page.locator('#${field.id}')`;
  if (field.ariaLabel) return `page.getByLabel('${escStr(field.ariaLabel)}')`;
  if (field.placeholder) return `page.getByPlaceholder('${escStr(field.placeholder)}')`;
  if (field.name)   return `page.locator('[name="${field.name}"]')`;
  return `page.locator('input[type="${field.type ?? 'text'}"]').first()`;
}

function escStr(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').slice(0, 35);
}
